### PR TITLE
Update Travis CI to use standard test script and go 1.9.x.

### PR DESCRIPTION
**Pull request by kevina**

### CODE REVIEW

**Comment by kevina** [comment]
More annoying `go vet` errors
```
swarm_test.go:119: result of (*peerstream.Swarm).String call not used
swarm_test.go:120: result of (*peerstream.Swarm).String call not used
```
Also see: https://github.com/libp2p/go-reuseport/pull/32 https://github.com/libp2p/go-libp2p/pull/245

**Comment by Stebalien** [comment]
I fixed the `go vet` error.

**Comment by kevina** [comment]
Okay, I rebased to meet our requirement that every commit passes the tests.

**Comment by Stebalien** [comment]
Something is trying to build `example` twice...

**Pull request merged**
