### PR TITLE
README/golint/examples: Standarize README, make golint happy, fix examples

### PR DESCRIPTION
**Pull request by hsanjuan**
This converts this into an standarized readme, adds correct badges, gx
instructions etc.

It sets me @hsanjuan as "maintainer", because there is no maintainer previously defined
so why not.

I have made golint happy too.

License: MIT
Signed-off-by: Hector Sanjuan <code@hector.link>

### CODE REVIEW

**Comment by hsanjuan** [comment]
@whyrusleeping I have sinked considerable time into getting `muxtest` subpackage work and I haven't managed to fix dependencies. Wanna give it a try?

**Comment by hsanjuan** [comment]
Related to https://github.com/ipfs/docs/issues/18

**Comment by whyrusleeping** [comment]
@hsanjuan I got muxtest working ish locally... I pushed this to master. Mind rebasing?

**Comment by whyrusleeping** [comment]
(did that while bubbling updates for something else, didnt notice this PR until afterwards)

**Comment by hsanjuan** [comment]
Thanks, will give it a try

**Comment by hsanjuan** [comment]
oh my... tests are green. I have suffered too much with this one...

**Comment by whyrusleeping** [comment]
Quickly! Merge it before it catches on! :)

Good work @hsanjuan

**Pull request merged**
